#!/usr/bin/python

# shNode Module: dht11/data
# output Temperature and Humidity from DHT11 sensor in XML

# Code based on:
# Copyright (c) 2014 Adafruit Industries
# Author: Tony DiCola

import sys, jxmlease, Adafruit_DHT

# GPIO Pin Number
pin = 27

# Try to grab a sensor reading.  Use the read_retry method which will retry up
# to 15 times to get a sensor reading (waiting 2 seconds between each retry).
humidity, temperature = Adafruit_DHT.read_retry(Adafruit_DHT.DHT11, pin)

# Note that sometimes you won't get a reading and
# the results will be null (because Linux can't
# guarantee the timing of calls to read the sensor).
# If this happens try again!
if humidity is not None and temperature is not None:
    temperature = temperature * 9/5.0 + 32
    data = ('\'temperature\': \'{0:0.1f}*F\', \'humidity\': \'{1:0.1f}%\''.format(temperature, humidity))
    data = '{\'dht11\': {'+data+'}}'
    print(jxmlease.emit_xml(eval(data)))
else:
	sys.exit(1)
