#!/usr/bin/python

# shNode Module: dht11/status
# output Temperature and Humidity from DHT11 sensor in human readable output

import sys, Adafruit_DHT

pin = 27

# Try to grab a sensor reading.  Use the read_retry method which will retry up
# to 15 times to get a sensor reading (waiting 2 seconds between each retry).
humidity, temperature = Adafruit_DHT.read_retry(Adafruit_DHT.DHT11, pin)

# Note that sometimes you won't get a reading and
# the results will be null (because Linux can't
# guarantee the timing of calls to read the sensor).
# If this happens try again!
if humidity is not None and temperature is not None:
    temperature = temperature * 9/5.0 + 32
    print('\ntemperature: {0:0.1f}*F\nhumidity: {1:0.1f}%\n'.format(temperature, humidity))
else:
    print('Failed to get reading. Try again!')
    sys.exit(1)
